export const MORTGAGE_APPLY_REQUEST = "MORTGAGE_APPLY_REQUEST";
export const MORTGAGE_APPLY_SUCCESS = "MORTGAGE_APPLY_SUCCESS";
export const MORTGAGE_APPLY_ERROR = "MORTGAGE_APPLY_ERROR";
export const GET_MORTGAGE_APPLICATION = "GET_MORTGAGE_APPLICATION"
export const MORTGAGE_APPLY_FOR_PREVIEW = "MORTGAGE_APPLY_FOR_PREVIEW"
export const GET_MORTGAGE_APPLICATION_ERROR = "GET_MORTGAGE_APPLICATION_ERROR";
export const GET_MORTGAGE_APPLICATION_REQUEST = "GET_MORTGAGE_APPLICATION_REQUEST";
