
export const lang = {
    EN: {
        HOME: 'Home',
        DASHBOARD: 'Dashboard',
        APPLICATIONS: 'Applications',
        PRODUCTS: 'Products',
        JAVOLIN_WALLET: 'Javolin Wallet',
        TOTAL_BALANCE: 'Total Balance',
        MAKE_DEPOSIT: 'Make Deposit',
        GET_STARTED: 'Get Started',
        SAVINGS: 'Savings',
        JAVOLIN_LOANS: 'Javolin Loans',
        JAVOLIN_LOANS_DESC: 'Apply for a mortgage and other loan products in minutes',
        JAVOLIN_LOANS_ACTION: 'Apply for a loan now',
        BUY_AIRTIME: 'Buy Airtime',
        BUY_AIRTIME_DESC: 'Top up airtime account',
        BUY_AIRTIME_ACTION: 'Send airtime now',
        SEND_MONEY: 'Send money',
        NEW: 'new!',
        COMING_SOON: 'coming soon!',
        SECURE_CREDIT_CARD: 'Secure credit card',
        LINE_GRAPH_DESC: 'Line Graph of transaction volumes by type',
        RECENT_TRANSACTION: 'Transactions',
        REFERENCE: 'Reference',
        INVEST: "Invest - Crypto",
        AMOUNT: 'Amount',
        TRANSACTION_TYPE: 'Transaction Type',
        DATE: 'Date',
        EDIT_PROFILE: 'Edit Profile',
        LOGOUT: 'Logout',
        HI: 'Hi',
        VIEW_ALL: 'View all',
        SERVICES: "Services",
        FUND_MY_WALLET: "Fund My wallet",
        FUND_MY_WALLET_MSG: "Top up your Javolin account",
        SEND_MONEY_MSG: "Send money to family and friends",
        TRANSFER_MONEY: "Transfer Money",
        TRANSFER_MONEY_MSG: "Move money between your accounts",
        PAYMENTS: "PAYMENTS",
        GOV_FEE: "Government Fees",
        APPLY_NOW: "apply now",
        LOAN: "LOAN",
        LOAN_DESC: "Loans",
        CARD: "CARD",
        CARD_DESC: "Secured Credit /Debit card",
        PORTFOLIO: "Porfolio",
        WALLET: "Wallet",
        PROFILE: "Profile",
        ACCOUNT_BALANCE: "Account balance",
        ACCOUNT_NUMBER: "Account number",
        WELCOME_MSG: "Welcome to Javolin! Get to know more about us. Watch this 60 seconds video",
        HELLO_THERE: "Hello to Javolin",
        FIRST_NAME: "First name",
        SURNAME: "Last Name",
        PHONE: "Phone number",
        PASSWORD:"Password",
        CONFIRM_PASSWORD: "Confirm Password",
        EMAIL: "Email",
        ADDRESS: "Physical Address",
        DOB: "Date of Birth",
        PRIVACY_AGREEMENT: "I agree with your Terms of Service and Privacy Notice",
        VERIFY_IDENTITY: "Verify your identity",
        VERIFY_IDENTITY_MSG: "Click here to set up your KYC to secure your account",
        EXCHANGE_RATE:"EXCHANGE RATES",
        MORTGAGE: "Mortage",
        MORTGAGE_WELCOME_MSG: "Mortgages are complicated. We make that our problem, not yours. Buy a home now.",
        ADD_CARD: "Add new card",
        MY_CARDS: "My Wallets",
        STATUS: "Status",
        GET_PREPAID: "Get Prepaid Cards",
        GET_PREPAID_MSG: "Get your physical or virtual card and make fast and seemless transactions",
        FUNDING_SOURCES: "Funding Sources",
        ADD_NEW_FUNDING: "Add new funding source",
        APPLICATION_STATUS: "Application Status",
        PREPAID: "Prepaid",
        PENDING: "Pending",
        VIEW:"View",
        PERSONAL_INFO: "Personal Information",
        CHANGE_PASSWORD:"Change Password",
        CHANGE_PIN: "Change Pin",
        GET_HELP: "Get Help",
        CONTACT: "Contact",
        QUESTION: "Question",
        ANSWER: "Answer",
        PASS_CHANGE_MSG: "You will need to answer this question to reset your password",
        CHANGE_PIN_MSG: "You will need to enter your current pin and a new pin",
        CURRENT_PIN: "Current Pin",
        NEW_PIN: "New Pin",
        SUBMIT: "Submit",
        CONTACT_INPUT_PLACEHOLDER: "Tell us how we can help",
        UPDATE: "Update",
        CHANGE_PROFILE_PIC: "Change Profile Picture",
        NEW_PASSWORD: "New Password",
        OLD_PASSWORD: "Old Password",
        SECURITY_QUESTIONS_INTRO: "You will need to answer this question to reset your password",
        CONTINUE: "Continue", 
        FUNDING_SOURCE: "FUNDING SOURCE", 
        FUND_FROM: "Fund from",
        FUNDING_DETAILS: "FUNDING DETAILS",
        FUNDING_DESTINATION: "Funding Destination",
        NOTE: "Note",
        OPTIONAL: "optional",
        FUND_WALLET: "Fund Wallet",
        DESTINATION: "destination",
        SELECT_ACCOUNT:"Select Account",
        NOTE_INPUT_PLACEHOLDER: "Eg. Stipend",
        SOURCE: "Source",
        SEND_FROM: "Send From",
        SEND_TO: "Send to",
        RECEPIENT:"Recepient",
        ACCOUNT_NAME: "Account Name",
        SELECT_NETWORK: "Select Network",
        BACK_TO_HOME: "Back to home",
        REVIEW:"Review",
        SENDING_FROM: "SENDING FROM",
        SENDING_TO: "SENDING TO",
        TRANSFER_FEE: "TRANSFER FEE",
        TOTAL_PAYABLE: "TOTAL PAYABLE",
        FOREIGN_EXCHANGE: "Foreign exchange",
        FOREIGN_EXCHANGE_DESC: "Get foreign exchange services.",
        PAYMENT_SENDMONEY: "Payments / Send Money"

    },
    FR: {
        HOME: 'Accueil',
        DASHBOARD: 'Tableau de bord',
        APPLICATIONS: 'Soumissions',
        PRODUCTS: 'Produits',
        JAVOLIN_WALLET: 'Portefeuille Javolin',
        TOTAL_BALANCE: 'Solde total',
        MAKE_DEPOSIT: 'Faire un dépôt',
        GET_STARTED: 'Commencer',
        SAVINGS: 'Des économies',
        JAVOLIN_LOANS: 'Prêts de Javolin',
        JAVOLIN_LOANS_DESC: 'Faites une demande de prêt hypothécaire et d\'autres produits de prêt en quelques minutes',
        JAVOLIN_LOANS_ACTION: 'Demander un prêt maintenant',
        BUY_AIRTIME: 'Acheter du temps d\'antenne',
        BUY_AIRTIME_DESC: 'Envoyer du temps d\'antenne à tous les réseaux',
        BUY_AIRTIME_ACTION: 'Envoyer du temps',
        SEND_MONEY: 'Envoyer de l\'argent',
        NEW: 'nouvelle',
        ADDRESS: "Adresse physique",
        COMING_SOON: 'Bientôt disponible',
        FIRST_NAME: "Prénom",
        SURNAME: "Nom de famille",
        PHONE: "Numéro de téléphone",
        EMAIL:"E-mail",
        SECURE_CREDIT_CARD: 'Carte de crédit sécurisée',
        LINE_GRAPH_DESC: 'Graphique linéaire des volumes de transactions par type',
        RECENT_TRANSACTION: 'Transactions',
        REFERENCE: 'Référence',
        INVEST: "Invest - Crypto",
        AMOUNT: 'Montante',
        TRANSACTION_TYPE: 'Type de transaction',
        DATE: 'Date',
        EDIT_PROFILE: 'Editer le profil',
        LOGOUT: 'Se déconnecter',
        HI: 'Salut',
        VIEW_ALL: 'Voir tout',
        SERVICES: "Prestations de service",
        FUND_MY_WALLET: "Financer mon portefeuille",
        FUND_MY_WALLET_MSG: "Rechargez votre compte Javolin",
        SEND_MONEY_MSG: "Envoyez de l'argent à votre famille et à vos amis",
        TRANSFER_MONEY: "Transférer de l'argent",
        TRANSFER_MONEY_MSG: "Transférer de l'argent entre vos comptes",
        PAYMENTS: "PAIEMENTS",
        GOV_FEE: "Frais gouvernementaux",
        APPLY_NOW: "appliquer maintenant",
        LOAN: "PRÊTE",
        LOAN_DESC: "Prêts",
        CARD: "CARTE",
        CARD_DESC: "Carte de crédit/débit sécurisée",
        PORTFOLIO: "Portefeuille",
        WALLET: "Porte monnaie",
        PROFILE: "Profil",
        ACCOUNT_BALANCE: "Solde du compte",
        ACCOUNT_NUMBER: "Numéro de compte",
        WELCOME_MSG: "Bienvenue à Javolin, nous sommes heureux de vous voir ici. Apprenez à mieux nous connaître. Regardez cette vidéo de 60 secondes",
        VERIFY_IDENTITY: "Vérifiez Votre Identité",
        VERIFY_IDENTITY_MSG: "Cliquez ici pour configurer votre KYC afin de sécuriser votre compte",
        EXCHANGE_RATE: "TAUX D'ÉCHANGE",
        MORTGAGE: "Hypothèque",
        MORTGAGE_WELCOME_MSG: "Les hypothèques sont compliquées. Nous en faisons notre problème, pas le vôtre. Achetez une maison maintenant.",
        ADD_CARD: "Ajouter une nouvelle carte",
        MY_CARDS: "Mes cartes",
        STATUS: "Statut",
        GET_PREPAID: "Obtenez des cartes prépayées",
        GET_PREPAID_MSG: "Obtenez votre carte physique ou virtuelle et effectuez des transactions rapides et transparentes",
        HELLO_THERE: "Bonjour",
        FUNDING_SOURCES: "Sources de financement",
        ADD_NEW_FUNDING: "Ajouter une nouvelle source de financement",
        APPLICATION_STATUS: "État de la candidature",
        PREPAID: "Prépayé",
        PENDING: "En attente",
        VIEW: "Voir",
        PERSONAL_INFO: "Renseignements personnels",
        CHANGE_PASSWORD: "Changer le mot de passe",
        CHANGE_PIN: "Changer d'épingle",
        GET_HELP: "Obtenir de l'aide",
        CONTACT: "Contacter",
        QUESTION: "Question",
        ANSWER: "Répondre",
        PASS_CHANGE_MSG: "Vous devrez répondre à cette question pour réinitialiser votre mot de passe",
        CHANGE_PIN_MSG: "Vous devrez entrer votre code PIN actuel et un nouveau code PIN",
        CURRENT_PIN: "Broche actuelle",
        NEW_PIN: "Nouvelle épingle",
        SUBMIT: "Soumettre",
        CONTINUE: "Continuez",
        CONTACT_INPUT_PLACEHOLDER: "Dites-nous comment nous pouvons aider",
        UPDATE:"Mise à jour",
        CHANGE_PROFILE_PIC :"Modifier la photo de profil",
        NEW_PASSWORD: "nouveau mot de passe",
        OLD_PASSWORD: "Ancien mot de passe",
        SECURITY_QUESTIONS_INTRO: "Vous devrez répondre à cette question pour réinitialiser votre mot de passe",
        FOREIGN_EXCHANGE: "Change",
        FOREIGN_EXCHANGE_DESC: "Obtenez des services de change.",
        PAYMENT_SENDMONEY: "Paiements / Envoyer de l'argent"
    }
}