export const MOMO_TRANSFER_REQUEST = "MOMO_TRANSFER_REQUEST";
export const MOMO_TRANSFER_SUCCESS = "MOMO_TRANSFER_SUCCESS";
export const MOMO_TRANSFER_ERROR = "MOMO_TRANSFER_ERROR";
export const JAVOLIN_TRANSFER_REQUEST = "JAVOLIN_TRANSFER_REQUEST";
export const JAVOLIN_TRANSFER_SUCCESS = "JAVOLIN_TRANSFER_SUCCESS";
export const JAVOLIN_TRANSFER_ERROR = "JAVOLIN_TRANSFER_ERROR";
export const GET_RECEIVER_ERROR = "GET_RECEIVER_ERROR"
export const GET_RECEIVER_REQUEST = "GET_RECEIVER_REQUEST"
export const GET_RECEIVER_SUCCESS = "GET_RECEIVER_SUCCESS"
export const AIRTIME_TRANSFER_REQUEST = "AIRTIME_TRANSFER_REQUEST"
export const AIRTIME_TRANSFER_SUCCESS = "AIRTIME_TRANSFER_SUCCESS"
export const AIRTIME_TRANSFER_ERROR = "AIRTIME_TRANSFER_ERROR"
export const GET_FEE_REQUEST = "GET_FEE_REQUEST"
export const GET_FEE_SUCCESS = "GET_FEE_SUCCESS"
export const GET_FEE_ERROR = "GET_FEE_ERROR"
export const GET_ERROR_MSG = "GET_ERROR_MSG"
export const GET_PREPAID_LINK_REQUEST = "GET_PREPAID_LINK_REQUEST"
export const GET_PREPAID_LINK_SUCCESS ="GET_PREPAID_LINK_SUCCESS"
export const GET_PREPAID_LINK_ERROR = "GET_PREPAID_LINK_ERROR" 

export const GET_PRERULES_REQUEST = "GET_PRERULES_REQUEST"
export const GET_PRERULES_SUCCESS = "GET_PRERULES_SUCCESS"
export const GET_PRERULES_ERROR = "GET_PRERULES_ERROR"

export const GET_RULES_REQUEST = "GET_RULES_REQUEST"
export const GET_RULES_SUCCESS = "GET_RULES_SUCCESS"
export const GET_RULES_ERROR = "GET_RULES_ERROR"
export const GET_FILTERED_RULES = "GET_FILTERED_RULES"
export const BENE_VALUES = "BENE_VALUES"

export const GET_RATE_REQUEST = "GET_RATE_REQUEST"
export const GET_RATE_SUCCESS = "GET_RATE_SUCCESS"
export const GET_RATE_ERROR = "GET_RATE_ERROR"

export const BOOK_RATE_REQUEST = "BOOK_RATE_REQUEST"
export const BOOK_RATE_SUCCESS = "BOOK_RATE_SUCCESS"
export const BOOK_RATE_ERROR = "BOOK_RATE_ERROR"


export const ADD_BENE_REQUEST = "ADD_BENE_REQUEST"
export const ADD_BENE_SUCCESS = "ADD_BENE_SUCCESS"
export const ADD_BENE_ERROR = "ADD_BENE_ERROR"
export const CLEAR_BENE_DATA = "CLEAR_BENE_DATA"

export const GET_BENE_REQUEST = "GET_BENE_REQUEST"
export const GET_BENE_SUCCESS = "GET_BENE_SUCCESS"
export const GET_BENE_ERROR = "GET_BENE_ERROR"

export const INSTRUCT_PAYMENT_REQUEST = "INSTRUCT_PAYMENT_REQUEST"
export const INSTRUCT_PAYMENT_SUCCESS = "INSTRUCT_PAYMENT_SUCCESS"
export const INSTRUCT_PAYMENT_ERROR = "INSTRUCT_PAYMENT_ERROR"

export const VALIDATE_IBAN_REQUEST = "VALIDATE_IBAN_REQUEST"
export const VALIDATE_IBAN_SUCCESS = "VALIDATE_IBAN_SUCCESS"
export const VALIDATE_IBAN_ERROR = "VALIDATE_IBAN_ERROR"


export const CHANGE_REGION_URL = "CHANGE_REGION_URL"

export const CREATE_WALLET_REQUEST = "CREATE_WALLET_REQUEST"
export const CREATE_WALLET_SUCCESS = "CREATE_WALLET_SUCCESS"
export const CREATE_WALLET_ERROR = "CREATE_WALLET_ERROR"