


export const SUBMIT_KYC_RESPONSE_REQUEST = "SUBMIT_KYC_RESPONSE_REQUEST";
export const SAVE_KYC_RESPONSE_SUCCESS = "SAVE_KYC_RESPONSE_SUCCESS";
export const SUBMIT_KYC_RESPONSE_ERROR = "SUBMIT_KYC_RESPONSE_ERROR";
export const SUBMIT_KYC_RESPONSE_SUCCESS = "SUBMIT_KYC_RESPONSE_SUCCESS"; 