    
export const GETTING_PERMISSIONS_REQUEST = "GETTING_PERMISSIONS_REQUEST"
export const GETTING_PERMISSIONS_SUCCESS = "GETTING_PERMISSIONS_SUCCESS"
export const GETTING_PERMISSIONS_ERROR = "GETTING_PERMISSIONS_ERROR"

export const GETTING_ROLES_REQUEST = "GETTING_ROLES_REQUEST"
export const GETTING_ROLES_SUCCESS = "GETTING_ROLES_SUCCESS"
export const GETTING_ROLES_ERROR = "GETTING_ROLES_ERROR"

export const ADDING_ROLE_REQUEST = "ADDING_ROLE_REQUEST"
export const ADDING_ROLE_SUCCESS = "ADDING_ROLE_SUCCESS"
export const ADDING_ROLE_ERROR = "ADDING_ROLE_ERROR"