    
export const GETTING_PERMISSIONS_REQUEST = "GETTING_PERMISSIONS_REQUEST"
export const GETTING_PERMISSIONS_SUCCESS = "GETTING_PERMISSIONS_SUCCESS"
export const GETTING_PERMISSIONS_ERROR = "GETTING_PERMISSIONS_ERROR"