name: Deploy Forex App to Production or Staging Server

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - staging

jobs:
  deploy-to-production:
    runs-on: ${{env.forex-app-production}}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Decode production environment variables
        if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
        run: echo "Merge to main branch detected. Decoding production environment variables..."
      - name: Assign rights
        run: chmod -R a+rwx /var/www/forex-app/actions-runner/forex_work/new-forex-app/new-forex-app/node_modules
      - name: Install dependencies
        run: npm install
      - name: Decode base64 string and create .env file
        env:
          ENV_VARS: ${{secrets.PRODUCTION_ENV_VARS}}
        run: |
          echo "${{env.ENV_VARS}}" | base64 --decode > /var/www/forex-app/actions-runner/forex_work/new-forex-app/new-forex-app/.env
          cat ".env"
      - name: Generate the build
        run: CI=false npm run build
      - name: Restart Nginx
        run: |
          cd ..
          sudo service nginx restart
  
  deploy-to-staging:
    runs-on: ${{env.forex-app-staging}}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Decode Staging environment variables
        if: ${{ github.event_name == 'push' && github.event.ref == 'refs/heads/staging' }}
        run: echo "Push to Staging branch detected. Decoding Staging environment variables..."
      - name: Assign rights
        run: chmod -R a+rwx /var/www/forex_staging/actions-runner/_work/new-forex-app/new-forex-app/node_modules
      - name: Install dependencies
        run: npm install
      - name: Decode base64 string and create .env file
        env:
          ENV_VARS: ${{secrets.STAGING_ENV_VARS}}
        run: |
          echo "${{env.ENV_VARS}}" | base64 --decode > /var/www/forex_staging/actions-runner/_work/new-forex-app/new-forex-app/.env
          cat ".env"
      - name: Generate the build
        run: CI=false npm run build
      - name: Restart Nginx
        run: |
          cd ..
          sudo service nginx restart

