export const ERROR_NOTIFICATION = "ERROR_NOTIFICATION";
export const SUCCESS_NOTIFICATION = "SUCCESS_NOTIFICATION";
export const ERROR_ALERT = "ERROR_ALERT";
export const SUCCESS_ALERT = "SUCCESS_ALERT";
export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE"
export const SET_DEFAULT_LANGUAGE = "SET_DEFAULT_LANGUAGE"
